<cfscript>
request.responseCommitted=false;

function jsonOut(required any data,numeric status=200){cfheader(statusCode=arguments.status,statusText=arguments.status>=400?"Error":"OK");cfcontent(type="application/json; charset=utf-8",reset=true);writeOutput(serializeJson(arguments.data));request.responseCommitted=true;abort;}
function redirectTo(required string location,numeric status=302){cfheader(statusCode=arguments.status,statusText="Found");cfheader(name="Location",value=arguments.location);request.responseCommitted=true;abort;}
function htmlOut(required string html,numeric status=200){cfheader(statusCode=arguments.status,statusText=arguments.status>=400?"Error":"OK");cfcontent(type="text/html; charset=utf-8",reset=true);writeOutput(arguments.html);request.responseCommitted=true;abort;}
function bodyJson(){var raw=getHttpRequestData().content;if(isBinary(raw))raw=charsetEncode(raw,"utf-8");if(!len(trim(raw&"")))return{};try{return deserializeJson(raw);}catch(any e){return{};}}
function routePath(){var p=listFirst(cgi.request_uri?:"/","?");p=reReplace(p,"^/index\.cfm","");if(!len(p))p="/";return p;}
function currentUser(){if(!structKeyExists(session,"user_id"))return{};return application.auth.getUser(session.user_id);}
function requireLogin(){var u=currentUser();if(!structCount(u))redirectTo("/login?next="&urlEncodedFormat(routePath()));return u;}
function requireAccess(required string section,string subsection=""){var u=requireLogin();if(!application.auth.hasAccess(u,arguments.section,arguments.subsection))jsonOut({ok:false,error:"You don't have permission to use this section."},403);return u;}
function requireAdmin(){var u=requireLogin();if(val(u.is_superadmin?:0)!=1)redirectTo("/");return u;}
function valForm(required array keys,any fallback=""){for(var k in arguments.keys)if(structKeyExists(form,k)&&len(trim(form[k]&"")))return form[k];return arguments.fallback;}
function valUrl(required string key,any fallback=""){return structKeyExists(url,arguments.key)?url[arguments.key]:arguments.fallback;}
function saveUploadAny(required array keys,required array extensions){var field="";for(var k in arguments.keys){if(structKeyExists(form,k)&&len(form[k]&"")){field=k;break;}}if(!len(field))throw(type="Logicore.Validation",message="Missing uploaded file: "&arrayToList(arguments.keys," / "));var result=fileUpload(application.uploadPath,field,"","makeunique",false);var ext=lCase(result.clientFileExt?:listLast(result.serverFile,"."));if(!arrayFindNoCase(arguments.extensions,ext)){try{fileDelete(result.serverDirectory&"/"&result.serverFile);}catch(any ignored){}throw(type="Logicore.Validation",message="Unsupported file type ."&ext&"; expected "&arrayToList(arguments.extensions,", "));}return result.serverDirectory&"/"&result.serverFile;}
function safeOutputName(any v="",string fallback="output"){var s=trim(arguments.v&"");if(!len(s))s=arguments.fallback;s=reReplace(s,"\.xlsx$","","one");return s;}
function sse(required struct payload){cfheader(name="Cache-Control",value="no-cache");cfheader(name="X-Accel-Buffering",value="no");cfcontent(type="text/event-stream; charset=utf-8",reset=true);writeOutput("data: "&serializeJson(arguments.payload)&chr(10)&chr(10));request.responseCommitted=true;abort;}
function portalAuthStruct(required struct u){var sections=[];var children=application.auth.accessibleChildren(arguments.u,"invoice-generator");if(arrayLen(children))arrayAppend(sections,"invoice-generator");for(var sec in ["sms-nonconforming","tbd2"])if(application.auth.hasAccess(arguments.u,sec))arrayAppend(sections,sec);if(len(application.auth.getRole(arguments.u,"training-tracker")))arrayAppend(sections,"training-tracker");return {username:u.username,isSuperadmin:val(u.is_superadmin?:0)==1,sections:sections,invoiceChildren:children,trainingRole:application.auth.getRole(u,"training-tracker")};}
function renderPortal(required struct u){var path=application.rootPath&"views/portal.html";if(!fileExists(path))return "<h1>Logicore Portal</h1><p>The generated portal shell is not present. Run the import-source-assets workflow.</p>";var html=fileRead(path,"utf-8");html=replace(html,"__AUTH_USERNAME__",encodeForHtml(u.username),"all");var authJson=replace(serializeJson(portalAuthStruct(u)),"</","<\/","all");html=replace(html,'<script src="/static/js/lucee-auth.js" defer></script>','<script>window.LOGICORE_AUTH='&authJson&';</script>'&chr(10)&'<script src="/static/js/lucee-auth.js" defer></script>',"one");return html;}
function renderLogin(string error=""){var err=len(arguments.error)?'<div class="error">'&encodeForHtml(arguments.error)&'</div>':"";var next=encodeForHtmlAttribute(valUrl("next","/"));return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Logicore Portal · Sign in</title><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"><style>.login-wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.login-card{width:min(420px,100%);background:#111720;border:1px solid #27313d;border-radius:14px;padding:28px}.login-card input{width:100%;margin:.35rem 0 1rem;background:#0a0d12;border:1px solid #334155;border-radius:8px;padding:.7rem;color:#eef2f6}.login-card button{width:100%;padding:.75rem;border-radius:8px;background:#2fd8a6;color:#07100d;font-weight:700}.error{margin-bottom:1rem;color:#f87171}</style></head><body><div class="login-wrap"><form class="login-card" method="post" action="/login"><img src="/static/logicore_logo.png" alt="Logicore" style="max-width:220px;margin:0 auto 22px"><h1 style="font-size:1.35rem;margin-bottom:1rem">Sign in</h1>'&err&'<label>Username</label><input name="username" autocomplete="username" required><label>Password</label><input name="password" type="password" autocomplete="current-password" required><input type="hidden" name="next" value="'&next&'"><button type="submit">Sign in</button></form></div></body></html>';}
function renderAdmin(required struct admin){var users=application.auth.listUsers();var out='<html><head><meta charset="utf-8"><title>Users & Permissions</title><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"><style>.wrap{max-width:1100px;margin:30px auto;padding:20px}.card{border:1px solid #334155;border-radius:10px;padding:16px;margin:14px 0;background:#111720}input,select{background:#0a0d12;border:1px solid #475569;border-radius:6px;padding:6px;color:#eef2f6}button{background:#2fd8a6;color:#07100d;padding:6px 10px;border-radius:6px}</style></head><body><div class="wrap"><p><a href="/">← Portal</a></p><h1 class="text-2xl">Users & Permissions</h1><div class="card"><h2>Create user</h2><form method="post" action="/admin/permissions/users/new"><input name="username" placeholder="Username" required> <input name="password" type="password" placeholder="Password" required> <input name="initials" maxlength="6" placeholder="Initials"> <label><input type="checkbox" name="is_superadmin"> Superadmin</label> <button>Create</button></form></div>';
for(var u in users){var perms=application.auth.getPermissions(u.id);out&='<div class="card"><h2>'&encodeForHtml(u.username)&(val(u.is_superadmin?:0)?' · Superadmin':'')&'</h2><form method="post" action="/admin/permissions/users/'&u.id&'/set"><label><input type="checkbox" name="invoice_generator" '&(structKeyExists(perms,"invoice-generator|")?'checked':'')&'> Invoice Generator (all)</label><div style="margin-left:20px">';for(var child in ["promethean","amc","tcl","philips","config"]){out&='<label style="margin-right:12px"><input type="checkbox" name="ig_'&child&'" '&(structKeyExists(perms,"invoice-generator|"&child)?'checked':'')&'> '&encodeForHtml(child)&'</label>';}out&='</div><label><input type="checkbox" name="sms_nonconforming" '&(structKeyExists(perms,"sms-nonconforming|")?'checked':'')&'> SMS NonConforming</label> <label>Training role <select name="training_role"><option value="">None</option>';for(var role in ["viewer","editor","admin"])out&='<option value="'&role&'" '&((perms["training-tracker|"]?:"")==role?'selected':'')&'>'&role&'</option>';out&='</select></label> <label><input type="checkbox" name="tbd2" '&(structKeyExists(perms,"tbd2|")?'checked':'')&'> Inventory Management</label> <button>Save permissions</button></form><form method="post" action="/admin/permissions/users/'&u.id&'/initials" style="margin-top:8px"><input name="initials" value="'&encodeForHtmlAttribute(u.initials?:"")&'" placeholder="Initials"><button>Save initials</button></form><form method="post" action="/admin/permissions/users/'&u.id&'/password" style="margin-top:8px"><input type="password" name="password" placeholder="New password"><button>Reset password</button></form>';if(u.id!=admin.id)out&='<form method="post" action="/admin/permissions/users/'&u.id&'/delete" style="margin-top:8px"><button style="background:#ef4444;color:white">Delete user</button></form>';out&='</div>';}out&='</div></body></html>';return out;}

var path=routePath();var method=uCase(cgi.request_method?:"GET");

// Inventory Management is a real mounted workspace (legacy permission key: tbd2).
if(left(path,len("/inventory-management"))=="/inventory-management"){include "routes/InventoryRoutes.cfm";abort;}
if(left(path,len("/training-tracker"))=="/training-tracker"){include "routes/TrainingRoutes.cfm";abort;}

// health / version
if(path=="/healthz")jsonOut({ok:true,status:"healthy",engine:"Lucee",version:"9.0-lucee"});
if(path=="/version")jsonOut({ok:true,version:"9.0-lucee",runtime:"Lucee CFML"});

// login/logout
if(path=="/login"){
    if(method=="POST"){var u=application.auth.authenticate(form.username?:"",form.password?:"");if(structCount(u)){sessionInvalidate();session.user_id=u.id;session.sid=replace(createUUID(),"-","","all");var dest=form.next?:url.next?:"/";if(!len(dest)||left(dest,1)!="/")dest="/";redirectTo(dest);}htmlOut(renderLogin("Incorrect username or password."),401);}
    if(structCount(currentUser()))redirectTo("/");htmlOut(renderLogin());
}
if(path=="/logout"){sessionInvalidate();redirectTo("/login");}

// main portal
if(path=="/"){var u=requireLogin();htmlOut(renderPortal(u));}

// admin
if(path=="/admin/permissions"&&method=="GET"){var admin=requireAdmin();htmlOut(renderAdmin(admin));}
if(path=="/admin/permissions/users/new"&&method=="POST"){requireAdmin();try{application.auth.createUser(form.username?:"",form.password?:"",structKeyExists(form,"is_superadmin"),form.initials?:"");}catch(any e){}redirectTo("/admin/permissions");}
var m=reFind("^/admin/permissions/users/([0-9]+)/(delete|password|initials|set)$",path,1,true);
if(m.len[1]){var admin=requireAdmin();var uid=val(mid(path,m.pos[2],m.len[2]));var action=mid(path,m.pos[3],m.len[3]);if(method!="POST")redirectTo("/admin/permissions");if(action=="delete"&&uid!=admin.id)application.auth.deleteUser(uid);else if(action=="password"&&len(form.password?:"")>=4)application.auth.updateUser(id=uid,password=form.password);else if(action=="initials")application.auth.updateUser(id=uid,initials=form.initials?:"");else if(action=="set"){
    for(var spec in [{s:"invoice-generator",f:"invoice_generator"},{s:"sms-nonconforming",f:"sms_nonconforming"},{s:"tbd2",f:"tbd2"}]){if(structKeyExists(form,spec.f))application.auth.setPermission(uid,spec.s);else application.auth.clearPermission(uid,spec.s);}
    for(var c in ["promethean","amc","tcl","philips","config"]){if(structKeyExists(form,"ig_"&c))application.auth.setPermission(uid,"invoice-generator",c);else application.auth.clearPermission(uid,"invoice-generator",c);}
    application.auth.clearPermission(uid,"training-tracker");if(len(form.training_role?:""))application.auth.setPermission(uid,"training-tracker","",form.training_role);
}redirectTo("/admin/permissions");}

// Config endpoints
if(path=="/config/serial_rules"||path=="/get_serial_rules"){requireAccess("invoice-generator","config");if(method=="GET")jsonOut({ok:true,rules:application.configService.getSerialRules().rules?:[]});var d=bodyJson();application.configService.saveSerialRules(structKeyExists(d,"rules")?d:{rules:d});jsonOut({ok:true});}
if(path=="/get_storage_prices"){requireAccess("invoice-generator","config");jsonOut({ok:true,prices:application.configService.getStoragePrices(),defaults:application.configService.storageDefaults()});}
if(path=="/set_storage_prices"){requireAccess("invoice-generator","config");var d=bodyJson();if(d.reset?:false)application.configService.resetStoragePrices();else application.configService.saveStoragePrices(d.prices?:d);jsonOut({ok:true,prices:application.configService.getStoragePrices(),defaults:application.configService.storageDefaults()});}
if(path=="/get_fedex_shipment_defaults"){requireAccess("invoice-generator","config");jsonOut({ok:true,defaults:application.configService.getFedexDefaults()});}
if(path=="/set_fedex_shipment_defaults"){requireAccess("invoice-generator","config");var d=bodyJson();application.configService.saveFedexDefaults(d.defaults?:d);jsonOut({ok:true,defaults:application.configService.getFedexDefaults()});}
if(path=="/get_philips_dimensions"){requireAccess("invoice-generator","config");var d=application.configService.getPhilipsDimensions();jsonOut({ok:true,dimensions:d,count:structCount(d)});}
if(path=="/upload_philips_dimensions"&&method=="POST"){requireAccess("invoice-generator","config");try{var p=saveUploadAny(["file","dimensions"],["xlsx"]);var d=application.configService.readDimensionsWorkbook(p);application.configService.savePhilipsDimensions(d);jsonOut({ok:true,count:structCount(d)});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/download_philips_dimensions"){requireAccess("invoice-generator","config");var name="Philips_Dimensions.xlsx";application.configService.writeDimensionsWorkbook(application.outputPath&name,application.configService.getPhilipsDimensions(),"Dimensions");application.outputs.register(name,"config");redirectTo("/download/"&urlEncodedFormat(name));}
if(path=="/get_philips_repair_cost"){requireAccess("invoice-generator","config");jsonOut({ok:true,rows:application.configService.getPhilipsRepairCost(),repair_cost:application.configService.getPhilipsRepairCost()});}
if(path=="/set_philips_repair_cost"){requireAccess("invoice-generator","config");var d=bodyJson();application.configService.savePhilipsRepairCost(d.rows?:d.repair_cost?:d);jsonOut({ok:true,rows:application.configService.getPhilipsRepairCost()});}
if(path=="/get_amc_dimensions"){requireAccess("invoice-generator","config");var d=application.configService.getAmcDimensions();jsonOut({ok:true,dimensions:d,count:structCount(d)});}
if(path=="/upload_amc_dimensions"&&method=="POST"){requireAccess("invoice-generator","config");try{var p=saveUploadAny(["file","dimensions"],["xlsx"]);var d=application.configService.readDimensionsWorkbook(p);application.configService.saveAmcDimensions(d);jsonOut({ok:true,count:structCount(d)});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/download_amc_dimensions"){requireAccess("invoice-generator","config");var name="AMC_Dimensions.xlsx";application.configService.writeDimensionsWorkbook(application.outputPath&name,application.configService.getAmcDimensions(),"Dimensions");application.outputs.register(name,"config");redirectTo("/download/"&urlEncodedFormat(name));}
if(path=="/get_amc_prices"){requireAccess("invoice-generator","config");jsonOut({ok:true,prices:application.configService.getAmcPrices(),defaults:application.configService.amcDefaults()});}
if(path=="/set_amc_prices"){requireAccess("invoice-generator","config");var d=bodyJson();if(d.reset?:false)application.configService.resetAmcPrices();else application.configService.saveAmcPrices(d.prices?:d);jsonOut({ok:true,prices:application.configService.getAmcPrices(),defaults:application.configService.amcDefaults()});}

// Workshop
if(path=="/sanitize"&&method=="POST"){requireAccess("invoice-generator","promethean");try{var raw=saveUploadAny(["raw_file","file","raw","repair_file"],["xlsx"]);var a=application.invoice.analyzeWorkshop(raw,valForm(["date_from","from","date-from"]),valForm(["date_to","to","date-to"]));session.workshop=a;jsonOut({ok:true,total_records:a.total_records,issues:a.issues,issue_count:a.issue_count,auto_count:a.auto_count,auto_corrections:a.auto_corrections});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/generate"&&method=="POST"){requireAccess("invoice-generator","promethean");try{if(!structKeyExists(session,"workshop"))throw(type="Logicore.State",message="No Workshop analysis is active. Validate the source file again.");var corr={};if(len(form.corrections?:""))corr=deserializeJson(form.corrections);var result=application.invoice.buildWorkshop(session.workshop,corr,safeOutputName(form.output_filename?:"","Promethean_Workshop_Invoice"));session.workshop_done=result;jsonOut({ok:true,output:result.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream"){requireAccess("invoice-generator","promethean");var d=session.workshop_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// Storage
if(path=="/analyze_storage"&&method=="POST"){requireAccess("invoice-generator","promethean");try{var inv=saveUploadAny(["inventory","inventory_file"],["csv"]);var sh=saveUploadAny(["shipping","shipping_file"],["csv"]);var rc=saveUploadAny(["receipt","receipts","receipt_file"],["csv"]);var fx=saveUploadAny(["fedex","fedex_file"],["xlsx"]);var whitelist="";try{whitelist=saveUploadAny(["whitelist","whitelist_file"],["xlsx"]);}catch(any ignored){}var a=application.invoice.analyzeStorage(inv,sh,rc,fx,val(valForm(["pallet_count","pallets"],0)),valForm(["date_from","from"]),valForm(["date_to","to"]),whitelist);session.storage=a;jsonOut({ok:true,unit_storage_count:arrayLen(a.unit_storage),unit_receipt_count:arrayLen(a.units_received),unit_picks_count:a.unit_picks_count,small_part_picks:a.small_part_picks,pallet_count:a.pallet_count,auto_spc_count:arrayLen(a.auto_spc_rows),unmatched:a.unmatched,review_unmatched:a.unmatched});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_storage"&&method=="POST"){requireAccess("invoice-generator","promethean");try{if(!structKeyExists(session,"storage"))throw(type="Logicore.State",message="No Storage analysis is active.");var include=[];if(len(form.confirmed_rows?:form.include_unmatched?:""))include=deserializeJson(form.confirmed_rows?:form.include_unmatched);var r=application.invoice.buildStorage(session.storage,safeOutputName(form.output_filename?:"","Promethean_Storage_Invoice"),include);session.storage_done=r;jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_storage"){requireAccess("invoice-generator","promethean");var d=session.storage_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// FedEx shipment upload
if(path=="/analyze_fedex_shipment"&&method=="POST"){requireAccess("invoice-generator","promethean");try{var raw=saveUploadAny(["raw","file","fedex_raw"],["xlsx"]);var a=application.invoice.analyzeFedexShipment(raw,valForm(["period_label","period"],dateFormat(now(),"mmmm yyyy")),valForm(["call_date","date"],dateFormat(now(),"yyyy-mm-dd")));session.fedex=a;jsonOut({ok:true,row_count:arrayLen(a.rows),defaulted_rows:a.defaulted_rows,skipped_rows:a.skipped_rows,total_price:a.total_price});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/build_fedex_shipment"&&method=="POST"){requireAccess("invoice-generator","promethean");try{if(!structKeyExists(session,"fedex"))throw(type="Logicore.State",message="No FedEx analysis is active.");var r=application.invoice.buildFedexShipment(session.fedex,safeOutputName(form.output_filename?:"","FedEx_Shipment_Upload"));session.fedex_done=r;jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_fedex_shipment"){requireAccess("invoice-generator","promethean");var d=session.fedex_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// Philips
if(path=="/analyze_philips"&&method=="POST"){requireAccess("invoice-generator","philips");try{var report=saveUploadAny(["report","file","month_end_report"],["xlsx"]);var a=application.invoice.analyzePhilips(report,val(valForm(["parts_sqft","parts_square_footage"],0)));session.philips=a;jsonOut({ok:true,inbound_count:a.inbound_count,outbound_count:a.outbound_count,repair_count:a.repair_count,harvest_count:a.harvest_count,missing_dimension_models:a.missing_dimension_models,demo_total_sqft:a.demo_total_sqft,service_total_sqft:a.service_total_sqft});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/generate_report_and_analyze"&&method=="POST"){requireAccess("invoice-generator","philips");try{var report=saveUploadAny(["report","file","month_end_report"],["xlsx"]);var a=application.invoice.analyzePhilips(report,val(valForm(["parts_sqft","parts_square_footage"],0)));session.philips=a;jsonOut({ok:true,inbound_count:a.inbound_count,outbound_count:a.outbound_count,repair_count:a.repair_count,harvest_count:a.harvest_count,missing_dimension_models:a.missing_dimension_models,demo_total_sqft:a.demo_total_sqft,service_total_sqft:a.service_total_sqft});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_philips"&&method=="POST"){requireAccess("invoice-generator","philips");try{if(!structKeyExists(session,"philips"))throw(type="Logicore.State",message="No Philips analysis is active.");var r=application.invoice.buildPhilips(session.philips,valForm(["invoice_title"],"TPV Philips Warehouse Invoice"),safeOutputName(form.output_filename?:"","TPV_Philips_Warehouse_Invoice"));session.philips_done=r;jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_philips"){requireAccess("invoice-generator","philips");var d=session.philips_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// AMC
if(path=="/analyze_amc"&&method=="POST"){requireAccess("invoice-generator","amc");try{var rec=saveUploadAny(["receiving"],["xlsx"]);var ship=saveUploadAny(["shipping"],["xlsx"]);var inv=saveUploadAny(["inventory"],["xlsx"]);var a=application.invoice.analyzeAMC(rec,ship,inv,valForm(["date_from","period_start","from"]),valForm(["date_to","period_end","to"]));session.amc=a;jsonOut({ok:true,receipt_count:a.receipt_count,ship_count:a.ship_count,total_sqft:a.total_sqft,additional_sqft:a.additional_sqft,missing_dimension_models:a.missing_dimension_models});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_amc"&&method=="POST"){requireAccess("invoice-generator","amc");try{if(!structKeyExists(session,"amc"))throw(type="Logicore.State",message="No AMC analysis is active.");var r=application.invoice.buildAMC(session.amc,valForm(["invoice_title"],"AMC Warehouse Invoice"),safeOutputName(form.output_filename?:"","AMC_Warehouse_Invoice"));session.amc_done=r;jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_amc"){requireAccess("invoice-generator","amc");var d=session.amc_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// TCL
if(path=="/analyze_tcl"&&method=="POST"){requireAccess("invoice-generator","tcl");try{var inv=saveUploadAny(["inventory","file"],["xlsx"]);var a=application.invoice.analyzeTCL(inv,valForm(["date_from","from"]),valForm(["date_to","to"]));session.tcl=a;jsonOut({ok:true,unit_groups:a.unit_groups,part_groups:a.part_groups,unit_count:a.unit_count,part_count:a.part_count});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/confirm_tcl"&&method=="POST"){requireAccess("invoice-generator","tcl");try{if(!structKeyExists(session,"tcl"))throw(type="Logicore.State",message="No TCL analysis is active.");var units=deserializeJson(form.unit_breakdowns?:"{}");var boxes=deserializeJson(form.box_breakdowns?:"{}");var r=application.invoice.buildTCL(session.tcl,units,boxes,safeOutputName(form.output_filename?:"","TCL_Warehouse_Invoice"));session.tcl_done=r;jsonOut({ok:true,output:r.filename});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/stream_tcl"){requireAccess("invoice-generator","tcl");var d=session.tcl_done?:{success:false,error:"No build result available."};d.type="done";d.success=!(structKeyExists(d,"error"));sse(d);}

// SMS NonConforming API
if(path=="/nonconforming/api/items"&&method=="GET"){var u=requireAccess("sms-nonconforming");var data=application.nonconforming.listItems(valUrl("q",""),valUrl("status",""),val(valUrl("limit",50)),val(valUrl("offset",0)));data.ok=true;data.next_number_preview=application.nonconforming.previewNextNumber(application.auth.initialsFor(u));jsonOut(data);}
if(path=="/nonconforming/api/items"&&method=="POST"){var u=requireAccess("sms-nonconforming");try{var item=application.nonconforming.addItem(bodyJson(),u,application.auth.initialsFor(u));jsonOut({ok:true,item:item});}catch(any e){jsonOut({ok:false,error:e.message},400);}}
if(path=="/nonconforming/api/next-number"){var u=requireAccess("sms-nonconforming");jsonOut({ok:true,next_number:application.nonconforming.previewNextNumber(application.auth.initialsFor(u))});}
if(path=="/nonconforming/api/export"){requireAccess("sms-nonconforming");var data=application.nonconforming.listItems(valUrl("q",""),valUrl("status",""),50000,0);var name=application.nonconforming.buildExport(data.items);application.outputs.register(name,"sms-nonconforming");redirectTo("/download/"&urlEncodedFormat(name));}
var nm=reFind("^/nonconforming/api/items/([0-9]+)(/label)?$",path,1,true);
if(nm.len[1]){requireAccess("sms-nonconforming");var id=val(mid(path,nm.pos[2],nm.len[2]));var isLabel=nm.len[3]>0;if(isLabel){var item=application.nonconforming.getItem(id);if(!structCount(item))jsonOut({ok:false,error:"Not found"},404);var zpl=application.nonconforming.buildZpl(item);if(valUrl("download",0)==1){cfheader(name="Content-Disposition",value='attachment; filename="'&item.number&'.zpl"');cfcontent(type="application/octet-stream",reset=true);writeOutput(zpl);abort;}jsonOut({ok:true,number:item.number,zpl:zpl});}if(method=="GET")jsonOut({ok:true,item:application.nonconforming.getItem(id)});if(method=="PUT"){try{jsonOut({ok:true,item:application.nonconforming.updateItem(id,bodyJson())});}catch(any e){jsonOut({ok:false,error:e.message},400);}}if(method=="DELETE")jsonOut({ok:true,deleted:application.nonconforming.deleteItem(id)});}

// Download generated files with persistent ownership markers.
var dm=reFind("^/download/(.+)$",path,1,true);
if(dm.len[1]){var u=requireLogin();var filename=urlDecode(mid(path,dm.pos[2],dm.len[2]));var subsection=application.outputs.subsection(filename);if(!len(subsection))jsonOut({ok:false,error:"File not found."},404);var allowed=subsection=="sms-nonconforming"?application.auth.hasAccess(u,"sms-nonconforming"):application.auth.hasAccess(u,"invoice-generator",subsection);if(!allowed)jsonOut({ok:false,error:"Not authorized."},403);var real=application.outputs.resolve(filename);if(!len(real))jsonOut({ok:false,error:"File not found."},404);cfheader(name="Content-Disposition",value='attachment; filename="'&getFileFromPath(real)&'"');cfcontent(file=real,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}

// Training Tracker routes
if(left(path,18)=="/training-tracker"){var u=requireLogin();var role=application.auth.getRole(u,"training-tracker");if(!len(role))redirectTo("/");var canEdit=listFindNoCase("admin,editor",role)>0;var isAdmin=role=="admin";var sub=removeChars(path,1,18);if(!len(sub))sub="/";
    if(sub=="/"&&method=="GET"){var weeks=application.training.weeks();var html='<html><head><meta charset="utf-8"><title>Training Tracker</title><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"></head><body><div style="max-width:1000px;margin:30px auto;padding:20px"><p><a href="/">← Logicore Portal</a></p><h1 style="font-size:2rem">Training Tracker</h1><p><a href="/training-tracker/people">Roster</a> · <a href="/training-tracker/reports">Reports</a></p>';if(canEdit)html&='<form method="post" action="/training-tracker/weeks/new"><input name="title" placeholder="Week title" required><input type="date" name="start_date"><button>Create week</button></form>';for(var w in weeks)html&='<div style="border:1px solid #334155;border-radius:10px;padding:14px;margin:12px 0"><a href="/training-tracker/weeks/'&w.id&'"><strong>Week '&w.week_number&': '&encodeForHtml(w.title)&'</strong></a><div>'&encodeForHtml(w.start_date?:"")&' · '&w.topic_count&' topics · '&w.session_count&' sessions</div></div>';html&='</div></body></html>';htmlOut(html);}
    if(sub=="/weeks/new"&&method=="POST"&&canEdit){var id=application.training.createWeek(form.title?:"Untitled",form.start_date?:"",form.notes?:"");redirectTo("/training-tracker/weeks/"&id);}
    var wm=reFind("^/weeks/([0-9]+)$",sub,1,true);if(wm.len[1]&&method=="GET"){var wid=val(mid(sub,wm.pos[2],wm.len[2]));var w=application.training.week(wid);if(!structCount(w))htmlOut("Not found",404);var html='<html><head><meta charset="utf-8"><title>'&encodeForHtml(w.title)&'</title><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"></head><body><div style="max-width:1000px;margin:30px auto;padding:20px"><p><a href="/training-tracker/">← Weeks</a></p><h1 style="font-size:2rem">'&encodeForHtml(w.title)&'</h1><h2>Topics</h2>';for(var t in w.topics)html&='<div style="padding:10px;border-bottom:1px solid #334155"><strong>'&encodeForHtml(t.title)&'</strong><p>'&encodeForHtml(t.lesson_plan?:"")&'</p></div>';if(canEdit)html&='<form method="post" action="/training-tracker/weeks/'&wid&'/topics"><input name="title" placeholder="Topic" required><textarea name="lesson_plan" placeholder="Lesson plan"></textarea><textarea name="key_points" placeholder="Key points"></textarea><button>Add topic</button></form>';html&='<h2 style="margin-top:24px">Sessions</h2>';for(var s in w.sessions)html&='<div style="padding:10px;border-bottom:1px solid #334155"><a href="/training-tracker/sessions/'&s.id&'">'&encodeForHtml(s.trainer_name)&'</a> · '&encodeForHtml(s.session_date?:"")&' · '&s.attended_count&' attended / '&s.signed_count&' signed</div>';if(canEdit)html&='<form method="post" action="/training-tracker/weeks/'&wid&'/sessions"><input name="trainer_name" placeholder="Trainer" required><input type="date" name="session_date"><input name="location" placeholder="Location"><button>Add session</button></form>';html&='</div></body></html>';htmlOut(html);}
    var tm=reFind("^/weeks/([0-9]+)/(topics|sessions)$",sub,1,true);if(tm.len[1]&&method=="POST"&&canEdit){var wid=val(mid(sub,tm.pos[2],tm.len[2]));var kind=mid(sub,tm.pos[3],tm.len[3]);if(kind=="topics")application.training.createTopic(wid,form.title?:"Untitled",form.lesson_plan?:"",form.key_points?:"");else application.training.createSession(wid,form.trainer_name?:"Unassigned",form.session_date?:"",form.location?:"");redirectTo("/training-tracker/weeks/"&wid);}
    if(sub=="/people"&&method=="GET"){var people=application.training.people();var html='<html><head><meta charset="utf-8"><title>Roster</title><link rel="stylesheet" href="/static/css/app.css"></head><body><div style="max-width:900px;margin:30px auto"><a href="/training-tracker/">← Weeks</a><h1>Roster</h1>';for(var p in people)html&='<p>'&encodeForHtml(p.name)&' · '&encodeForHtml(p.email?:"")&'</p>';if(canEdit)html&='<form method="post" action="/training-tracker/people"><input name="name" required placeholder="Name"><input name="email" placeholder="Email"><button>Add person</button></form>';html&='</div></body></html>';htmlOut(html);}
    if(sub=="/people"&&method=="POST"&&canEdit){application.training.addPerson(form.name?:"",form.email?:"");redirectTo("/training-tracker/people");}
    var sm=reFind("^/sessions/([0-9]+)$",sub,1,true);if(sm.len[1]&&method=="GET"){var sid=val(mid(sub,sm.pos[2],sm.len[2]));var att=application.training.attendance(sid);var html='<html><head><meta charset="utf-8"><title>Training Session</title><link rel="stylesheet" href="/static/css/app.css"></head><body><div style="max-width:900px;margin:30px auto"><a href="/training-tracker/">← Training Tracker</a><h1>Attendance / Sign-off</h1>';for(var a in att)html&='<form method="post" action="/training-tracker/sessions/'&sid&'/attendance/'&a.person_id&'" style="padding:10px;border-bottom:1px solid #334155"><strong>'&encodeForHtml(a.name)&'</strong> <label><input type="checkbox" name="attended" '&(val(a.attended)?'checked':'')&'> Attended</label> <input name="signature" value="'&encodeForHtmlAttribute(a.signature?:"")&'" placeholder="Signature"><button>Save</button></form>';html&='</div></body></html>';htmlOut(html);}
    var am=reFind("^/sessions/([0-9]+)/attendance/([0-9]+)$",sub,1,true);if(am.len[1]&&method=="POST"&&canEdit){var sid=val(mid(sub,am.pos[2],am.len[2]));var pid=val(mid(sub,am.pos[3],am.len[3]));application.training.setAttendance(sid,pid,structKeyExists(form,"attended"));if(len(trim(form.signature?:"")))application.training.sign(sid,pid,form.signature);redirectTo("/training-tracker/sessions/"&sid);}
    if(sub=="/reports"&&method=="GET"){var r=application.training.report();htmlOut('<html><head><meta charset="utf-8"><title>Training Reports</title><link rel="stylesheet" href="/static/css/app.css"></head><body><div style="max-width:900px;margin:30px auto"><a href="/training-tracker/">← Weeks</a><h1>Reports</h1><p>Weeks: '&r.weeks&'</p><p>Sessions: '&r.sessions&'</p><p>Roster: '&r.people&'</p><p>Attended: '&r.attended&'</p><p>Signed: '&r.signed&'</p></div></body></html>');}
    htmlOut("Not found",404);
}

jsonOut({ok:false,error:"Not found",path:path},404);
</cfscript>
