<cfscript>
function invBase(required string title){return '<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'&encodeForHtml(arguments.title)&' · Inventory Management</title><link rel="stylesheet" href="/static/css/tailwind.css"><link rel="stylesheet" href="/static/css/app.css"><style>.inv{max-width:1180px;margin:26px auto;padding:0 20px}.card{background:##111720;border:1px solid ##334155;border-radius:10px;padding:16px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px}.muted{color:##94a3b8}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid ##334155;text-align:left;vertical-align:top}input,select,textarea{background:##0a0d12;border:1px solid ##475569;color:##eef2f6;border-radius:6px;padding:7px}button,.btn{display:inline-block;background:##2fd8a6;color:##07100d;border-radius:6px;padding:7px 11px;font-weight:700}.danger{background:##ef4444;color:white}a{color:##58d9ff}</style></head><body><div class="inv"><p><a href="/">← Logicore Portal</a></p><nav><a href="/inventory-management/">Dashboard</a> · <a href="/inventory-management/import">Import</a> · <a href="/inventory-management/imports">Imports</a> · <a href="/inventory-management/shipping/all">Shipping</a> · <a href="/inventory-management/quality">Quality</a></nav><h1 style="font-size:2rem;margin-top:12px">'&encodeForHtml(arguments.title)&'</h1>';}
function invEnd(){return '</div></body></html>';}
function invEventTable(required array rows){var h='<div style="overflow:auto"><table><thead><tr><th>Date</th><th>Event</th><th>Model</th><th>Serial</th><th>MSO</th><th>Source</th></tr></thead><tbody>';for(var e in arguments.rows)h&='<tr><td>'&encodeForHtml(e.event_at?:"")&'</td><td>'&encodeForHtml(e.event_type?:"")&'</td><td>'&encodeForHtml(e.model_number?:"")&'</td><td>'&encodeForHtml(e.serial_number?:"")&'</td><td>'&encodeForHtml(e.mso_number?:"")&'</td><td>'&encodeForHtml(e.original_filename?:"")&'</td></tr>';return h&'</tbody></table></div>';}
function sendTextDownload(required string data,required string filename,required string type){cfheader(name="Content-Disposition",value='attachment; filename="'&getFileFromPath(arguments.filename)&'"');cfcontent(type=arguments.type,reset=true);writeOutput(arguments.data);request.responseCommitted=true;abort;}

iu=requireLogin();if(!application.auth.hasAccess(iu,"tbd2"))redirectTo("/");
ip=removeChars(path,1,len("/inventory-management"));if(!len(ip))ip="/";

if(ip=="/"&&method=="GET"){
    d=application.inventory.dashboard();h=invBase("Inventory Management")&'<div class="grid"><div class="card"><strong>'&d.assets&'</strong><div class="muted">Serials</div></div><div class="card"><strong>'&d.events&'</strong><div class="muted">Lifecycle events</div></div><div class="card"><strong>'&d.cases&'</strong><div class="muted">MSOs</div></div><div class="card"><strong>'&d.imports&'</strong><div class="muted">Imports</div></div></div><div class="card"><form action="/inventory-management/search" method="get"><input name="q" required placeholder="Serial, MSO, or model" style="min-width:320px"><select name="kind"><option value="auto">Auto</option><option value="serial">Serial</option><option value="mso">MSO</option><option value="model">Model</option></select> <button>Search</button></form></div><h2>Recent imports</h2><table><tr><th>File</th><th>Source</th><th>Rows</th><th>Events</th><th>Imported</th></tr>';for(b in d.latest)h&='<tr><td>'&encodeForHtml(b.original_filename)&'</td><td>'&encodeForHtml(b.source_name)&'</td><td>'&b.rows_read&'</td><td>'&b.events_added&'</td><td>'&encodeForHtml(b.imported_at)&'</td></tr>';htmlOut(h&'</table>'&invEnd());
}
if(ip=="/search"&&method=="GET"){r=application.inventory.search(url.q?:"",url.kind?:"auto");if(!len(r.kind))redirectTo("/inventory-management/");redirectTo("/inventory-management/"&r.kind&"/"&urlEncodedFormat(r.value));}

sm=reFind("^/serial/(.+)$",ip,1,true);if(sm.len[1]&&method=="GET"){value=urlDecode(mid(ip,sm.pos[2],sm.len[2]));d=application.inventory.serialDetail(value);if(!structCount(d))htmlOut(invBase("Not found")&'<p>No serial found for '&encodeForHtml(value)&'.</p>'&invEnd(),404);h=invBase("Serial "&d.serial_number)&'<div class="card"><strong>Last model:</strong> '&encodeForHtml(d.last_model?:"")&'<br><strong>Models seen:</strong> '&encodeForHtml(arrayToList(d.models,", "))&'<br><strong>MSOs:</strong> '&encodeForHtml(arrayToList(d.msos,", "))&'</div>'&invEventTable(d.events)&invEnd();htmlOut(h);}
mm=reFind("^/mso/(.+)$",ip,1,true);if(mm.len[1]&&method=="GET"){value=urlDecode(mid(ip,mm.pos[2],mm.len[2]));d=application.inventory.msoDetail(value);if(!structCount(d))htmlOut(invBase("Not found")&'<p>No MSO found for '&encodeForHtml(value)&'.</p>'&invEnd(),404);htmlOut(invBase("MSO "&d.mso_number)&'<div class="card"><strong>Case:</strong> '&encodeForHtml(d.case_number?:"")&'<br><strong>Serials:</strong> '&encodeForHtml(arrayToList(d.serials,", "))&'</div>'&invEventTable(d.events)&invEnd());}
md=reFind("^/model/(.+?)(/export\.csv)?$",ip,1,true);if(md.len[1]){value=urlDecode(mid(ip,md.pos[2],md.len[2]));if(find("/export.csv",ip))sendTextDownload(application.inventory.modelCsv(value),"Inventory_Model_"&reReplace(value,"[^A-Za-z0-9_-]","_","all")&".csv","text/csv; charset=utf-8");d=application.inventory.modelDetail(value);htmlOut(invBase("Model "&value)&'<p>'&d.total&' matching lifecycle events · <a href="/inventory-management/model/'&urlEncodedFormat(value)&'/export.csv">Export CSV</a></p>'&invEventTable(d.events)&invEnd());}

if(ip=="/import"&&method=="GET")htmlOut(invBase("Import operational data")&'<div class="card"><p>Supported: Receiving, Shipping, Inventory, Repair Data, and FedEx master exports. CSV, XLSX and XLSM are accepted; source type is detected from columns.</p><form method="post" enctype="multipart/form-data"><input type="file" name="files" multiple required accept=".csv,.xlsx,.xlsm"> <button>Import</button></form></div>'&invEnd());
if(ip=="/import"&&method=="POST"){uploaded=fileUploadAll(application.uploadPath,"","makeunique",true,["csv","xlsx","xlsm"]);results=[];for(f in uploaded){try{arrayAppend(results,application.inventory.importFile(f.serverDirectory&"/"&f.serverFile,f.clientFile));}catch(any e){arrayAppend(results,{filename:f.clientFile,error:e.message});}try{fileDelete(f.serverDirectory&"/"&f.serverFile);}catch(any ignored){}}h=invBase("Import results");for(r in results)h&='<div class="card"><strong>'&encodeForHtml(r.filename?:"")&'</strong><br>'&(structKeyExists(r,"error")?'<span style="color:##f87171">'&encodeForHtml(r.error)&'</span>':((r.duplicate_file?:false)?'Duplicate file — skipped.':'Source: '&encodeForHtml(r.source?:"")&' · '&(r.rows?:0)&' rows · '&(r.events?:0)&' events'))&'</div>';htmlOut(h&invEnd());}
if(ip=="/imports"&&method=="GET"){h=invBase("Import history")&'<table><tr><th>ID</th><th>File</th><th>Source</th><th>Rows</th><th>Events</th><th>Duplicates</th><th>Imported</th></tr>';for(b in application.inventory.imports())h&='<tr><td>'&b.id&'</td><td>'&encodeForHtml(b.original_filename)&'</td><td>'&encodeForHtml(b.source_name)&'</td><td>'&b.rows_read&'</td><td>'&b.events_added&'</td><td>'&b.duplicates_skipped&'</td><td>'&encodeForHtml(b.imported_at)&'</td></tr>';htmlOut(h&'</table>'&invEnd());}

if(ip=="/shipping/all"||ip=="/shipping/model"||ip=="/shipping/all/export.csv"||ip=="/shipping/model/export.csv"||ip=="/shipping/all/export.xlsx"||ip=="/shipping/model/export.xlsx"){
    range=application.inventory.shippingRange(url.preset?:"last7",url.start?:"",url.end?:"");model=ip contains "/model"?(url.model?:""):"";rep=application.inventory.shippingHistory(range,model);
    if(right(ip,11)=="/export.csv")sendTextDownload(application.inventory.shippingCsv(rep.rows),"Shipping_History_"&(len(model)?reReplace(model,"[^A-Za-z0-9_-]","_","all"):"All_Models")&"_"&range.start&"_to_"&range.end&".csv","text/csv; charset=utf-8");
    if(right(ip,12)=="/export.xlsx"){fn=application.inventory.shippingXlsx(rep.rows,range,"Shipping History",model);cfheader(name="Content-Disposition",value='attachment; filename="'&fn&'"');cfcontent(file=application.outputPath&fn,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}
    h=invBase(len(model)?"Shipping history · "&model:"Shipping history")&'<div class="card"><form method="get"><select name="preset"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="last7">Last 7 Days</option><option value="last30">Last 30 Days</option><option value="custom">Custom Range</option></select><input type="date" name="start" value="'&range.start&'"><input type="date" name="end" value="'&range.end&'">';if(ip contains "/model"){h&='<select name="model"><option value="">Choose model</option>';for(mx in application.inventory.shippingModels())h&='<option '&(compareNoCase(mx,model)==0?'selected':'')&'>'&encodeForHtml(mx)&'</option>';h&='</select>';}h&='<button>Apply</button></form><p>'&range.start_display&' – '&range.end_display&' · '&rep.summary.shipments&' shipments · '&rep.summary.models&' models · '&rep.summary.serials&' serials · '&rep.summary.msos&' MSOs</p><a href="/inventory-management'&ip&'/export.csv?'&cgi.query_string&'">CSV</a> · <a href="/inventory-management'&ip&'/export.xlsx?'&cgi.query_string&'">Excel</a></div>'&invEventTable(rep.rows)&invEnd();htmlOut(h);
}

if(ip=="/quality/quality")redirectTo("/inventory-management/quality"&(len(cgi.query_string?:"")?"?"&cgi.query_string:""));
if(ip=="/quality"&&method=="POST"){f=fileUpload(application.uploadPath,"reference","","makeunique",true,["json"]);try{application.inventory.installReference(f.serverDirectory&"/"&f.serverFile);}finally{try{fileDelete(f.serverDirectory&"/"&f.serverFile);}catch(any ignored){}}redirectTo("/inventory-management/quality");}
if(ip=="/quality/override"&&method=="POST"){application.inventory.saveOverride(form.serial?:"",form.approved_model?:"",form.note?:"");redirectTo("/inventory-management/quality?audit=1");}
if(ip=="/quality/override/delete"&&method=="POST"){application.inventory.deleteOverride(form.serial?:"");redirectTo("/inventory-management/quality?audit=1");}
if(ip=="/quality/whitelist"&&method=="POST"){application.inventory.saveWhitelist(form.kind?:"",form.value?:"",form.note?:"");redirectTo("/inventory-management/quality?audit=1");}
if(ip=="/quality/whitelist/delete"&&method=="POST"){application.inventory.deleteWhitelist(form.kind?:"",form.value?:"");redirectTo("/inventory-management/quality?audit=1");}
if(ip=="/quality/export.csv"&&method=="GET"){audit=application.inventory.qualityAudit();if(!structCount(audit))redirectTo("/inventory-management/quality");sendTextDownload(application.inventory.qualityCsv(audit),"Promethean_Current_Inventory_Audit.csv","text/csv; charset=utf-8");}
if(ip=="/quality/export.xlsx"&&method=="GET"){audit=application.inventory.qualityAudit();if(!structCount(audit))redirectTo("/inventory-management/quality");rows=[];for(i in audit.issues)arrayAppend(rows,{"Record Type":"Issue","Issue Type":i.issue_type?:"","Severity":i.severity?:"","Serial Number":i.serial_number?:"","Grade":i.grade?:"","Recorded Model":i.model_number?:"","Expected / Approved Model":i.expected_model?:"","Warehouse":i.details.warehouse?:"","Rack":i.details.rack?:"","Bin":i.details.bin?:"","Source File":i.original_filename?:"","Source Row":i.source_row_key?:"","Detail":i.message?:""});for(i in audit.unmatched)arrayAppend(rows,{"Record Type":"Needs model mapping","Issue Type":"Unmatched serial/model","Severity":"review","Serial Number":i.serial_number?:"","Grade":i.grade?:"","Recorded Model":i.model_number?:"","Expected / Approved Model":"","Warehouse":i.details.warehouse?:"","Rack":i.details.rack?:"","Bin":i.details.bin?:"","Source File":i.original_filename?:"","Source Row":i.source_row_key?:"","Detail":i.message?:""});fn="Promethean_Current_Inventory_Audit.xlsx";application.excel.writeWorkbook(application.outputPath&fn,[{name:"Current Inventory Audit",headers:["Record Type","Issue Type","Severity","Serial Number","Grade","Recorded Model","Expected / Approved Model","Warehouse","Rack","Bin","Source File","Source Row","Detail"],rows:rows}]);cfheader(name="Content-Disposition",value='attachment; filename="'&fn&'"');cfcontent(file=application.outputPath&fn,type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",reset=true);abort;}
if(ip=="/quality"&&method=="GET"){ref=application.inventory.reference();manual=structCount(ref)?application.inventory.manualQuality(url.serial?:"",url.model?:"",url.part?:""):{};audit=(structCount(ref)&&(url.audit?:"")=="1")?application.inventory.qualityAudit():{};h=invBase("Promethean inventory quality")&'<div class="card">'&(structCount(ref)?'<strong>Reference installed.</strong>':'<strong>No Promethean reference installed.</strong>')&'<form method="post" enctype="multipart/form-data"><input type="file" name="reference" accept=".json" required> <button>Install / replace reference</button></form></div>';if(structCount(ref)){h&='<div class="card"><form method="get"><input name="serial" placeholder="Serial" value="'&encodeForHtmlAttribute(url.serial?:"")&'"><input name="model" placeholder="Recorded model" value="'&encodeForHtmlAttribute(url.model?:"")&'"><input name="part" placeholder="Part" value="'&encodeForHtmlAttribute(url.part?:"")&'"> <button>Check</button></form>';if(structCount(manual))h&='<pre>'&encodeForHtml(serializeJson(manual))&'</pre>';h&='</div><div class="card"><a class="btn" href="/inventory-management/quality?audit=1">Run current-inventory audit</a></div>';}
    if(structCount(audit)){h&='<div class="grid"><div class="card">'&audit.inventory_records&'<div>Inventory records</div></div><div class="card">'&audit.errors&'<div>Errors</div></div><div class="card">'&audit.warnings&'<div>Warnings</div></div><div class="card">'&audit.unmatched_count&'<div>Needs mapping</div></div></div><p><a href="/inventory-management/quality/export.csv">Export CSV</a> · <a href="/inventory-management/quality/export.xlsx">Export Excel</a></p><h2>Issues</h2>'&invEventTable(audit.issues)&'<h2>Needs mapping</h2>'&invEventTable(audit.unmatched)&'<div class="card"><h2>Approve serial mapping</h2><form method="post" action="/inventory-management/quality/override"><input name="serial" placeholder="Serial" required><input name="approved_model" placeholder="Approved model" required><input name="note" placeholder="Note"><button>Approve</button></form><h2>Global whitelist</h2><form method="post" action="/inventory-management/quality/whitelist"><select name="kind"><option value="part">Part / value</option><option value="model">Model</option></select><input name="value" required><input name="note" placeholder="Note"><button>Approve globally</button></form></div>';}
    htmlOut(h&invEnd());
}
htmlOut(invBase("Not found")&'<p>Inventory Management route not found.</p>'&invEnd(),404);
</cfscript>
