component output=false {
    property name="datasource";

    function init(required string datasource) {
        variables.datasource = arguments.datasource;
        return this;
    }

    void function initSchema() {
        queryExecute("CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(120) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, is_superadmin INT NOT NULL DEFAULT 0, initials VARCHAR(12), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)", {}, {datasource:variables.datasource});
        queryExecute("CREATE TABLE IF NOT EXISTS permissions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, section VARCHAR(120) NOT NULL, subsection VARCHAR(120), role VARCHAR(40), CONSTRAINT fk_permissions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE)", {}, {datasource:variables.datasource});
        queryExecute("CREATE INDEX IF NOT EXISTS idx_permissions_user ON permissions(user_id)", {}, {datasource:variables.datasource});
    }

    void function init() {
        initSchema();
        var q = queryExecute("SELECT COUNT(*) AS c FROM users", {}, {datasource:variables.datasource});
        if (q.c[1] == 0) createUser("admin", "admin", true, "AD");
    }

    struct function sections() {
        return {
            "invoice-generator": {label:"Invoice Generator", children:{promethean:"Promethean", amc:"AMC", tcl:"TCL", philips:"Philips", config:"Config"}},
            "sms-nonconforming": {label:"SMS NonConforming"},
            "training-tracker": {label:"Training Tracker", roles:["admin","editor","viewer"]},
            "tbd2": {label:"TBD 2"}
        };
    }

    private string function passwordHash(required string password, required string salt) {
        return hash(arguments.password & ":" & arguments.salt, "SHA-256", "UTF-8", 120000);
    }

    private string function makePassword(required string password) {
        var salt = lCase(replace(createUUID(), "-", "", "all"));
        return salt & "$" & passwordHash(arguments.password, salt);
    }

    boolean function verifyPassword(required string password, required string stored) {
        if (!find("$", arguments.stored)) return false;
        var bits = listToArray(arguments.stored, "$", true);
        if (arrayLen(bits) != 2) return false;
        return compareNoCase(bits[2], passwordHash(arguments.password, bits[1])) == 0;
    }

    numeric function createUser(required string username, required string password, boolean isSuperadmin=false, string initials="") {
        var result = {};
        queryExecute(
            "INSERT INTO users(username,password_hash,is_superadmin,initials) VALUES(:u,:p,:s,:i)",
            {
                u:{value:trim(arguments.username), cfsqltype:"cf_sql_varchar"},
                p:{value:makePassword(arguments.password), cfsqltype:"cf_sql_varchar"},
                s:{value:arguments.isSuperadmin ? 1 : 0, cfsqltype:"cf_sql_integer"},
                i:{value:len(trim(arguments.initials)) ? uCase(trim(arguments.initials)) : javacast("null", ""), null:!len(trim(arguments.initials)), cfsqltype:"cf_sql_varchar"}
            },
            {datasource:variables.datasource, result:"result"}
        );
        return result.generatedKey ?: 0;
    }

    struct function authenticate(required string username, required string password) {
        var q = queryExecute("SELECT * FROM users WHERE LOWER(username)=LOWER(:u)", {u:{value:trim(arguments.username), cfsqltype:"cf_sql_varchar"}}, {datasource:variables.datasource});
        if (q.recordCount != 1 || !verifyPassword(arguments.password, q.password_hash[1])) return {};
        return rowToStruct(q, 1);
    }

    struct function getUser(required numeric id) {
        var q = queryExecute("SELECT * FROM users WHERE id=:id", {id:{value:arguments.id,cfsqltype:"cf_sql_bigint"}}, {datasource:variables.datasource});
        return q.recordCount ? rowToStruct(q,1) : {};
    }

    array function listUsers() {
        var q = queryExecute("SELECT * FROM users ORDER BY username", {}, {datasource:variables.datasource});
        return queryToArray(q);
    }

    void function updateUser(required numeric id, string password="", any isSuperadmin=javacast("null",""), any initials=javacast("null","")) {
        if (len(arguments.password)) {
            queryExecute("UPDATE users SET password_hash=:p WHERE id=:id", {p:makePassword(arguments.password),id:arguments.id}, {datasource:variables.datasource});
        }
        if (!isNull(arguments.isSuperadmin)) {
            queryExecute("UPDATE users SET is_superadmin=:s WHERE id=:id", {s:arguments.isSuperadmin?1:0,id:arguments.id}, {datasource:variables.datasource});
        }
        if (!isNull(arguments.initials)) {
            queryExecute("UPDATE users SET initials=:i WHERE id=:id", {i:uCase(trim(arguments.initials)),id:arguments.id}, {datasource:variables.datasource});
        }
    }

    void function deleteUser(required numeric id) {
        queryExecute("DELETE FROM users WHERE id=:id", {id:arguments.id}, {datasource:variables.datasource});
    }

    boolean function hasAccess(required struct user, required string section, string subsection="") {
        if (!structCount(arguments.user)) return false;
        if (val(arguments.user.is_superadmin ?: 0) == 1) return true;
        var params = {uid:arguments.user.id, sec:arguments.section};
        var sql = "SELECT id FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL";
        var q = queryExecute(sql, params, {datasource:variables.datasource});
        if (q.recordCount) return true;
        if (!len(arguments.subsection)) return false;
        params.sub = arguments.subsection;
        q = queryExecute("SELECT id FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", params, {datasource:variables.datasource});
        return q.recordCount > 0;
    }

    string function getRole(required struct user, required string section) {
        if (!structCount(arguments.user)) return "";
        if (val(arguments.user.is_superadmin ?: 0) == 1) return "admin";
        var q = queryExecute("SELECT role FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", {uid:arguments.user.id,sec:arguments.section}, {datasource:variables.datasource});
        return q.recordCount ? (q.role[1] ?: "") : "";
    }

    array function accessibleChildren(required struct user, required string section) {
        var registry = sections();
        if (!structKeyExists(registry,arguments.section) || !structKeyExists(registry[arguments.section],"children")) return [];
        var children = registry[arguments.section].children;
        if (hasAccess(arguments.user, arguments.section)) return structKeyArray(children);
        var q = queryExecute("SELECT subsection FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NOT NULL", {uid:arguments.user.id,sec:arguments.section}, {datasource:variables.datasource});
        var out=[];
        for (var row in q) arrayAppend(out,row.subsection);
        return out;
    }

    struct function getPermissions(required numeric userId) {
        var q = queryExecute("SELECT section,subsection,role FROM permissions WHERE user_id=:id", {id:arguments.userId}, {datasource:variables.datasource});
        var out={};
        for (var row in q) out[row.section & "|" & (row.subsection ?: "")] = len(row.role ?: "") ? row.role : "access";
        return out;
    }

    void function setPermission(required numeric userId, required string section, string subsection="", string role="access") {
        if (len(arguments.subsection)) {
            queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", {uid:arguments.userId,sec:arguments.section,sub:arguments.subsection}, {datasource:variables.datasource});
            queryExecute("INSERT INTO permissions(user_id,section,subsection,role) VALUES(:uid,:sec,:sub,:role)", {uid:arguments.userId,sec:arguments.section,sub:arguments.subsection,role:arguments.role=="access"?javacast("null",""):arguments.role}, {datasource:variables.datasource});
        } else {
            queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", {uid:arguments.userId,sec:arguments.section}, {datasource:variables.datasource});
            queryExecute("INSERT INTO permissions(user_id,section,subsection,role) VALUES(:uid,:sec,NULL,:role)", {uid:arguments.userId,sec:arguments.section,role:arguments.role=="access"?javacast("null",""):arguments.role}, {datasource:variables.datasource});
        }
    }

    void function clearPermission(required numeric userId, required string section, string subsection="") {
        if (len(arguments.subsection)) queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection=:sub", {uid:arguments.userId,sec:arguments.section,sub:arguments.subsection}, {datasource:variables.datasource});
        else queryExecute("DELETE FROM permissions WHERE user_id=:uid AND section=:sec AND subsection IS NULL", {uid:arguments.userId,sec:arguments.section}, {datasource:variables.datasource});
    }

    string function initialsFor(required struct user) {
        var explicit = uCase(trim(arguments.user.initials ?: ""));
        if (len(explicit)) return explicit;
        var username = arguments.user.username ?: "";
        var normalized = reReplace(username,"[._-]+"," ","all");
        var parts = listToArray(normalized," ");
        if (arrayLen(parts)>=2) return uCase(left(parts[1],1)&left(parts[2],1));
        return len(username)>=2 ? uCase(left(username,2)) : "XX";
    }

    private struct function rowToStruct(required query q, required numeric rowNumber) {
        var s={};
        for (var col in listToArray(arguments.q.columnList)) s[col]=arguments.q[col][arguments.rowNumber];
        return s;
    }

    private array function queryToArray(required query q) {
        var a=[];
        for (var i=1;i<=arguments.q.recordCount;i++) arrayAppend(a,rowToStruct(arguments.q,i));
        return a;
    }
}
